name: "Continuous Integration"

on:
  pull_request:
    branches:
      - master
      - "*.x"
  push:
    branches:
      - master
      - "*.x"
  schedule:
    - cron: "42 4 * * *"

env:
  fail-fast: true

jobs:
  sqlite:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
          
    steps:
    - uses: actions/checkout@v2
    
    - uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php-version }}"
        coverage: "pcov"

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: upscheme-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Setup config
      run: echo "<?php return ['driver' => 'pdo_sqlite', 'path' => 'sqlite.test']; ?>" > tests/config.php

    - name: "Run PHPUnit"
      run: "vendor/bin/phpunit --coverage-clover=coverage.xml"
